'use client'

import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })

const hiddenStyle = {
    height: '1px',
    width: '1px',
    position: 'absolute',
    overflow: 'hidden',
}

export default function Home() {

  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [isEmailValid, setIsEmailValid] = useState(false);
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');

  useEffect(() => {
    setIsEmailValid(email.includes('@'))
  }, [email])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Next.js Example Control Page</h1>

        <form
            style={{
                display: 'flex',
                flexDirection: 'column',
                gap: '1em',
            }}
        >
            <label for='name' style={hiddenStyle}>Your Name</label>
            <input
                style={{
                    padding: '0.5em',
                }}
                type={'text'}
                id={'name'}
                name={'name'}
                placeholder={'Your Name'}
                value={name}
                onChange={(e) => setName(e.target.value)}
            ></input>

            <label for='email' style={hiddenStyle}>Your Email</label>
            <input
                style={{
                    padding: '0.5em',
                }}
                type={'email'}
                id={'email'}
                name={'email'}
                placeholder={'Your Email'}
                value={email}
                onChange={(e) => setEmail(e.target.value)}
            ></input>

            <label for='subject-input' style={hiddenStyle}>Subject</label>
            <select
                style={{
                    padding: '0.5em',
                }}
                name="subject"
                id="subject-input"
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
            >
                <option value="">Select Subject</option>
                <option value="option-one">Option One</option>
                <option value="option-two">Option Two</option>
            </select>

            <label for='message' style={hiddenStyle}>Message</label>
            <textarea
                style={{
                    padding: '0.5em',
                }}
                id={'message'}
                name={'message'}
                placeholder={'Your Message'}
                rows={10}
                value={message}
                onChange={(e) => setMessage(e.target.value)}
            ></textarea>

            <button
                style={{
                    width: '100%',
                    margin: '0.5em 0',
                    padding: '0.5rem',
                    color: 'white',
                    backgroundColor: 'red',
                    cursor: "pointer",
                }}
                onClick={(event) => {
                    event.preventDefault();
                    alert(`
                        Submit Clicked!
                        - Name: ${name}
                        - Email: ${email}
                        - Subject: ${subject}
                        - Message: ${message}
                    `)
                }}
            >
                Submit
            </button>
        </form>

        <Link
            href={'/'}
            style={{
                display: 'block',
                margin: '1em',
                textAlign: 'center',
            }}
        >
            View Library Page
        </Link>

      </main>
    </>
  )
}
